name: Deploy Lambda Function

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Install zip tool
        run: sudo apt-get install zip -y

      - name: Create Zip file for Lambda function
        run: zip -r example-nest-modules.zip dist node_modules

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:us-east-1:324037296112:function:example-nest-api \
            --zip-file fileb://example-nest-modules.zip